### ISSUE TITLE
No files found "./db-acces.js"

### ISSUE THREAD

**Issue by atalayio** [torikushiii/DiscordTwitterBot#2]
The full error is: 

Error: Cannot find module './db-access.js'
Require stack:
- C:\Users\Emin\Desktop\Twitter-Discord-Bot\DiscordTwitterBot\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at C:\Users\Emin\Desktop\Twitter-Discord-Bot\DiscordTwitterBot\index.js:2:2
    at Object.<anonymous> (C:\Users\Emin\Desktop\Twitter-Discord-Bot\DiscordTwitterBot\index.js:33:3)    
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Emin\\Desktop\\Twitter-Discord-Bot\\DiscordTwitterBot\\index.js'
  ]
}

Node.js v18.16.0

This bot using mongo but I don't know how I create db-acces.js file with mongo parameters? Can you help me please?

**Comment by torikushiii** [comment]
here's the db-access sample

```
(function () {
	process.env.MONGO_IP = "123";
	process.env.MONGO_PORT = "321";

	process.env.MONGO_DB_NAME = "";
})();
```

**Comment by atalayio** [comment]
Thanks! It solved but here the next error: 

11:18:35 <WARN:SentinelModule> User twitter_user not found, ignoring
CustomError: No users found
    at SentinelSingleton.fetchTimeline (C:\Users\Administrator\Desktop\Twitter-Bot\DiscordTwitterBot\core\singletons\sentinel\index.js:59:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {     
  [cause]: undefined
}

**Comment by torikushiii** [comment]
because you'll need to add at least 1 valid user on `channels.json` before continuing

and just a warning if you want to self-host this bot, all the `sentinels` folders modules is not yet completed and commited because workaround for Twitter/X somewhat annoying to do and need a thousands of accounts to generate

**Comment by atalayio** [comment]
My channels.json like this:
[
"username
]
should be like that or what? And btw can't I use self hosted this bot?

**Comment by torikushiii** [comment]
you're missing a single double quotation mark after "username

and to answer the last one, yes somewhat (at least for now), since it missing a component that handles accounts to fetch the data since Twitter/X is patching the easy workarounds
