### ISSUE TITLE
Cannot find module 'node:events'

### ISSUE THREAD

**Issue by Williej926** [torikushiii/DiscordTwitterBot#4]
Hello, I am wondering what the issue with this is. Here is the stack trace.

```
(node:1689) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node:events'
Require stack:
- /home/ubuntu/DiscordTwitterBot/node_modules/discord.js/src/client/BaseClient.js
- /home/ubuntu/DiscordTwitterBot/node_modules/discord.js/src/index.js
- /home/ubuntu/DiscordTwitterBot/core/classes/command.js
- /home/ubuntu/DiscordTwitterBot/core/index.js
- /home/ubuntu/DiscordTwitterBot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ubuntu/DiscordTwitterBot/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

**Comment by torikushiii** [comment]
do you know what Node version are you using, you can try typing `node -v` into your terminal

**Comment by Williej926** [comment]
Yeah I am running 14.16.1

**Comment by torikushiii** [comment]
You might want to update your Node version since discord.js won't work on that version.

And just for heads up, this bot no longer working since 2 days ago since Twitter/X patched my method of getting timelines, I don't know if I can get any workaround since I've tried every possible way.
